services:
  backend:
    build:
      context: ./backend
    env_file:
      - ./.env.production
    volumes:
      - cloudvault-data:/app/src/data

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  cloudvault-data: